apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "content-api.fullname" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ include "content-api.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "content-api.fullname" . }}
        version: {{ .Values.image.tag | default .Chart.AppVersion }}
    spec:
      containers:
      - env:
        - name: API_USERNAME
          valueFrom:
            secretKeyRef:
              key: api_user
              name: app-creds
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              key: api_pass
              name: app-creds
        - name: LOG_LEVEL
          value: {{ .Values.logLevel }}
        - name: CONTACT_API_HOST
          valueFrom:
            secretKeyRef:
              key: contact_api_host
              name: services
        - name: CONTACT_API_PORT
          valueFrom:
            secretKeyRef:
              key: contact_api_port
              name: services
        - name: CONTACT_API_PROTOCOL
          valueFrom:
            secretKeyRef:
              key: contact_api_protocol
              name: services
        - name: USERS_API_HOST
          valueFrom:
            secretKeyRef:
              key: users_api_host
              name: services
        - name: USERS_API_PROTOCOL
          valueFrom:
            secretKeyRef:
              key: users_api_protocol
              name: services
      {{- if eq .Values.global.env "dev" }}
        image: "content-api:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Never
      {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
      {{- end }}
        name: {{ include "content-api.fullname" . }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: tcp-content
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        resources: {}
        livenessProbe:
          exec:
            command:
            - cat
            - /app/package.json
          initialDelaySeconds: 5
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /healthz
            port: tcp-content
          initialDelaySeconds: 15
          failureThreshold: 3
          periodSeconds: 10
      - image: redis
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          name: tcp-redis
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
