{{- if eq .Values.global.env "prod" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "content-api.fullname" . }}
spec:
  hosts:
  - "{{ include "content-api.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
  - "{{ include "content-api.fullname" . }}.{{ .Release.Namespace }}.beantownpub.com"
  - "beantownpub.com"
  - "www.beantownpub.com"

  gateways:
  - istio-ingress/web-gateway
  - mesh # applies to all the sidecars in the mesh
  http:
  - route:
    - destination:
        port:
          number: {{ .Values.containerPort }}
        host: "{{ include "content-api.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
        subset: {{ include "content-api.fullname" . }}
{{- end }}
