appName: content-api
aws:
  accessKeyId:
  secretAccessKey:
  region:
  secretName:
database:
  enabled: false
image:
  repository: jalgraves/content-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

containerPort: 5033

ingress:
  enabled: false

logLevel: INFO
